### ISSUE TITLE
SPI Module: read_data propagation bug

### ISSUE THREAD

**Issue by ana-pgodoy** [TeresaReLo/TOP_FIFO_Modules#1]
Hi Teresa.
According with the specification, the LOAD state must pass the data read from the FIFO memory to the shift_reg, however the data isn't being propagated to the register. Instated, data that was before the reading is being saved.
This behavior may be related to the read_en being asserted one clock cycle after the LOAD state rather during the state.

![image](https://github.com/user-attachments/assets/13f6f79c-2274-4246-b33a-e42caeb5a193)

**Comment by TeresaReLo** [comment]
Hi Ana-

I already solved that problem in the RTL design. There was a problem with the state machine using state instead of next state value, but because it is taking 1 clock cycle to assign the values to the local variables, a new state was required to be implemented in order to active the read_en signal only in the LOAD state allowing us to assign the data read from the FIFO memory to the shift_reg the next clock cycle ensuring that we are reading the correct data and not the previous value that was before the LOAD state.

In the following screenshot you can see that in the LOAD state the read_en signal is active, and the data from the FIFO read_data is being saved and in the next clock cycle read in the shift_reg and ready to be serialized in the SHIFT state. 

![image](https://github.com/user-attachments/assets/8453d8b0-e5f9-4d86-925b-a8ed5cabe892)

**Comment by ana-pgodoy** [comment]
Hi,  
I tested the property again and I also added a new assertion to test this behavior and the design is working fine now. I will attach a screenshot of the formal tool as soon as possible.
